Repository wecode-bootcamp-korea/13-grafolWEo-frontend, pull requests merged in 2020-10, with the labels that each got.

#1 [grafolWEo 홍효정] Modify: 컴포넌트 Class, ClassName, Route명 변경
  .eslintrc.json
  package-lock.json
  package.json
  public/Data/List/CATEGORY.json
  public/Data/List/LISTBANNERTAGS.json
  public/Data/List/POPULARLIST.json
  public/Data/memo.txt
  src/Pages/WorksList/Components/ListCategory.js
  src/Pages/WorksList/Components/ListTag.js
  src/Pages/WorksList/Components/PopularCreator.js
  src/Pages/WorksList/WorksList.js
  src/Pages/WorksList/WorksList.scss
  src/Routes.js
  src/Styles/common.scss
  src/Styles/reset.scss
  src/config.js
Labels: Status: 수정 요청

#5 [grafolWEo 김보경] Add:Detail 페이지 레이아웃 구현
  .eslintrc.json
  package-lock.json
  package.json
  public/Data/DetailPages/ARTWORKDETAILS.json
  public/Images/cat.jpeg
  public/Images/cute.jpeg
  public/Images/ellipsis.png
  public/Images/hearteyes.png
  public/Images/memo.txt
  public/Images/share.png
  public/Images/sp_grafolio_ratio.png
  public/Images/starred.png
  public/Images/sunglasses.png
  src/Components/DetailPages/Comment.js
  src/Components/DetailPages/Comment.scss
  src/Components/DetailPages/CommentList.js
  src/Components/DetailPages/CommentList.scss
  src/Components/DetailPages/DetailPages.js
  src/Components/DetailPages/DetailPages.scss
  src/Components/DetailPages/LikeEmoji.js
  src/Components/DetailPages/LikeEmoji.scss
  src/Components/DetailPages/memo.txt
  src/Routes.js
  src/config.js
  src/index.js
Labels: Status: 리뷰 요청

#3 [grafolWEo 홍효정] Fix: 수정요청 리뷰 반영, 컨플릭트 해결
  debug.log
  package-lock.json
  package.json
  public/Data/Wallpaper/DISCOVERCOLORS.json
  public/Data/Wallpaper/DISCOVERTAGS.json
  public/Data/Wallpaper/DISCOVERTYPE.json
  public/Data/Wallpaper/EDITORSPICKSLIDES.json
  public/Data/Wallpaper/EDITORSPICKSLIDESCOPY.json
  public/Data/Wallpaper/EDITORSPICKTAGS.json
  public/Data/Wallpaper/TOPCREATORS.json
  public/Images/bg_flicking_grd.png
  public/Images/sp_collection.png
  public/index.html
  src/Pages/Wallpaper/Components/DiscoverCardViewItem.js
  src/Pages/Wallpaper/Components/DiscoverColorList.js
  src/Pages/Wallpaper/Components/DiscoverTagList.js
  src/Pages/Wallpaper/Components/DiscoverTypeList.js
  src/Pages/Wallpaper/Components/Slide.js
  src/Pages/Wallpaper/Components/TopCreator.js
  src/Pages/Wallpaper/Wallpaper.js
  src/Pages/Wallpaper/Wallpaper.scss
  src/Pages/WorksList/Components/PopularCreator.js
  src/Routes.js
  src/Styles/common.scss
  src/Styles/mixin.scss
  src/config.js
Labels: Status: 리뷰 요청

#2 [grafolWEo 조연정] Add: Login Page validation
  package-lock.json
  public/Data/data.json
  public/Images/GrafolWeo.png
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/Routes.js
  src/index.js
Labels: Status: 수정 요청

#4 [grafolWEo 조연정]Modify: SignUp 페이지 리팩토링
  public/Data/data.json
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/config.js
Labels: Status: 리뷰 요청

#6 [grafolWEo 임수현] Add: Main 페이지 레이아웃 구현
  .eslintrc.json
  debug.log
  package-lock.json
  public/Data/CardList/data.json
  public/Data/Category/categoryData.json
  src/Components/CardList/CardWrap.js
  src/Components/CardList/CardWrap.scss
  src/Components/CardList/Components/Card.js
  src/Components/CardList/Components/Card.scss
  src/Pages/Main/Category/Categories.js
  src/Pages/Main/Category/Category.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/config.js
  src/index.js
  src/index.scss
Labels: Status: 리뷰 요청

#9 [조연정 grafolweo]Modify: login page 리팩토링 + conflict 해결
  public/Images/exclamation-mark.png
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/SignUp/SignUp.js
  src/config.js
Labels: Status: 리뷰 요청

#7 [grafolWEo 조연정]Add: Navbar, resolved conflict
  public/Data/Logindata/Logindata.json
  public/Images/bell.png
  public/Images/magnifying-glass.png
  public/Images/menu.png
  public/Images/upload.png
  public/Images/user.png
  src/Components/Navbar/Navbar.js
  src/Components/Navbar/Navbar.scss
  src/Components/Navbar/memo.txt
  src/Pages/Login/Login.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#11 [grafolWEo 임수현] Add: Feeds 페이지 구현
  src/Pages/Feeds/Feeds.js
  src/Pages/Feeds/Feeds.scss
  src/Pages/Main/Category/Categories.js
  src/Routes.js
  src/config.js
Labels: Status: Accepted

#13 [grafolWEo 조연정] Modify:conflict 해결, nav로직수정 및 footer component 추가
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Footer/memo.txt
  src/Components/Navbar/Navbar.js
  src/Components/Navbar/Navbar.scss
  src/Pages/Login/Login.js
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#10 [grafolWEo 임수현] Fix: conflict 및 버그 해결
  public/Data/List/CATEGORY.json
  src/Components/Navbar/Navbar.js
  src/Pages/Feeds/Feeds.js
  src/Pages/Main/Category/Categories.js
  src/Pages/WorksList/Components/ListCategory.js
  src/Pages/WorksList/Components/PopularCreator.js
  src/Pages/WorksList/Components/WorksListNew.js
  src/Pages/WorksList/Components/WorksListRecommend.js
  src/Pages/WorksList/WorksList.js
  src/Pages/WorksList/WorksList.scss
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#15 [grafolWEo 임수현] Refactoring: console.log 삭제
  src/Components/Navbar/Navbar.js
  src/Components/Navbar/Navbar.scss
  src/Pages/WorksList/Components/PopularCreator.js
  src/Pages/WorksList/WorksList.js
  src/config.js
Labels: Status: Accepted

#17 Fix: Detail Page modified
  public/Data/DetailPages/ARTWORKDETAILS.json
  public/Images/left.png
  public/Images/right.png
  src/Pages/DetailPages/DetailPages.js
Labels: Status: Accepted

#12 [grafolWEo 홍효정] Add: Wallpaper Detail page 레이아웃, 데이터 연결
  src/Components/CardList/Components/Card.js
  src/Components/CardList/Components/Card.scss
  src/Components/Navbar/Navbar.js
  src/Components/Navbar/Navbar.scss
  src/Components/Wallpaper/CardViewItem.js
  src/Components/Wallpaper/CardViewItem.scss
  src/Pages/DetailPages/Comment.js
  src/Pages/DetailPages/DetailPages.js
  src/Pages/DetailPages/DetailPages.scss
  src/Pages/DetailPages/LikeEmoji.js
  src/Pages/DetailPages/LikeEmoji.scss
  src/Pages/Feeds/Feeds.js
  src/Pages/Feeds/Feeds.scss
  src/Pages/Login/Login.js
  src/Pages/Main/Category/Category.scss
  src/Pages/Main/Main.scss
  src/Pages/SignUp/SignUp.js
  src/Pages/Wallpaper/Components/Slide.js
  src/Pages/Wallpaper/Wallpaper.js
  src/Pages/WallpaperDetail/WallpaperDetail.js
  src/Pages/WallpaperDetail/WallpaperDetail.scss
  src/Pages/WorksList/WorksList.scss
  src/Routes.js
  src/config.js
  src/index.js
Labels: Status: 수정 요청
